# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Conservatorium Maastricht Foundation
    url: 
    weight: 10
  - name: About
    url: about
    weight: 20
  - name: Who are we?
    pageRef: about/goals/index
    parent: About
    weight: 1
  - name: Meet the board
    pageRef: about/bestuur/index
    parent: About
    weight: 2
  - name: Financial statements
    pageRef: about/jaarrekening/index
    parent: About
    weight: 3
  - name: Partners
    pageRef: about/partners/index
    parent: About
    weight: 3
  - name: Our musicians
    url: musici
    weight: 40
  - name: For students
    url: student
    weight: 50
  - name: Support us
    url: sponsoring
    weight: 60
  - name: Contact
    url: contact
    weight: 70
